### ISSUE TITLE
How to change Date picker theme from blue to other color?

### ISSUE THREAD

**Issue by MaheshPeri19** [m3uzz/date_time_picker#1]
Hi,

Thanks for this package. Very good and highly customizable. 

How change default theme of blue color to other color and also how to remove edit button ?

If possible, please do date time picker as a widget instead of opening like popup.

**Comment by hslbetto** [comment]
Hi,

The widget use the app theme, so, you can change it on MaterialApp(ThemeData theme ...). 
The datepicker and timepicker use the primarySwatch color from ThemeData.

About open the date time picker as a page instead a popup, I have no plans to do this too soon, but I will consider it in a next version, thanks.
For now, maybe you can use CalendarDatePicker widget, I think it will fit your needs.

**Comment by maheshperi** [comment]
Okay. Thank you.

I will change it in MaterialApp theme.
