### ISSUE TITLE
Failed assertion !initialDate.isAfter(lastDate) when initialValue is empty string

### ISSUE THREAD

**Issue by sarbogast** [m3uzz/date_time_picker#16]
When I set the initialValue of the field to be the empty string, and lastDate in the past, when I try to open the date picker, I get an exception because date time picker is opened with `DateTime.now()` as a default, which breaks the assertion that initial date must be before `lastDate`. It would be better to add a `initialDatePickerDate` field for that purpose so that we can keep initial value empty and still work with date time picker dialog properly.

**Comment by sarbogast** [comment]
I created [this pull request](https://github.com/m3uzz/date_time_picker/pull/17) to solve this issue.

**Comment by hslbetto** [comment]
Very good, I liked the idea. Thanks for the contribution
