### ISSUE TITLE
First date after current date is not possible when initialvalue is null

### ISSUE THREAD

**Issue by TKalo** [m3uzz/date_time_picker#27]
When setting firstDate to a value after the current date and the initialValue is null, this error is shown:
!initialDate.isBefore(firstDate)
I have looked in the code and it is because a null initialValue will set initialDate to current date, eg.:
line 717:   initialDate: _dDate ?? DateTime.now(),

Solution:
The internal initialDate should be set to firstDate if initialValue is null.

EDIT:
I've looked further in the code, and there seems to be a parameter named "initialDate" on the DateTimePicker.
This would solve my issue, given that setting "initialDate" still leaves the textfield empty.
However, I cannot use this parameter in my code, despite having the latest version.
Is this parameter a bug fix that simply hasn't been released yet?

**Comment by hslbetto** [comment]
In version 2.0.0 this feature is already working

**Comment by kamleshwebtech** [comment]
@TKalo If date_time_picker team is working on this topic then with due respect, please do not close this topic/issue otherwise other users will post this issue again and again. Thanks.

**Comment by TKalo** [comment]
My understanding was from @hslbetto that the bug had already been fixed and the solution released. If this is not the case I agree, the issue should have remained open.
