### ISSUE TITLE
Using default suggested time does not fill time in textfield.

### ISSUE THREAD

**Issue by siteware** [m3uzz/date_time_picker#3]
I'm using a DateTimePicker with type: DateTimePickerType.dateTimeSeparate.

When tapping on the time field a time picker dialog opens with the current time. 
Pressing OK closes the dialog but does not fill the text field with a time value.

This behavior does work correctly for the date picker, but not for the time picker.

**Comment by hslbetto** [comment]
Thanks. It was fixed
