### ISSUE TITLE
Meridan Differentiation Fails when selected "12:00"

### ISSUE THREAD

**Issue by imcoffeefreak** [m3uzz/date_time_picker#4]
When selected **12:00** in the time picker it  displays AM or PM based on selected but when coverting to **Timestamp**  via JS it displays it has **AM** always****

**Comment by hslbetto** [comment]
@imcoffeefreak thanks about the notification, and it was fixed. 
But don't forget to specify the application language in material localization, it make the widget work correctly. Look at the example script.
