### ISSUE TITLE
calendarTitle and other parameters does not follow when creating a time picker

### ISSUE THREAD

**Issue by MostafaHassan** [m3uzz/date_time_picker#5]
DateTimePicker with the following type: DateTimePickerType.time 
will not use multiple parameters. One example being the calendarTitle

**Comment by hslbetto** [comment]
The date_time_picker uses the showTimePicker, it is a flutter original component, and it has just 5 parameters and have no title, it just show the time.

**Comment by MostafaHassan** [comment]
@hslbetto yes, but the helpText works as a title, and the cancelText and confirmText could be helpful to use, as it works in the showdatePicker and not showTimePicker.

Is it possible to fix the problem by adding the following to _showTimePickerDialog()
helpText: widget.calendarTitle,
cancelText: widget.cancelText,
confirmText: widget.confirmText,

**Comment by hslbetto** [comment]
showTimePicker is a native flutter plugin that call the time dialog from device and it has just 5 parameters, and none are about style. To change cancel button name or ok button, you can do this through material localization properties.
showDatePicker is almost the same, but has much more parameters, and you can control directly the style and the dialog texts.

**Comment by MostafaHassan** [comment]
@hslbetto Alright, thanks :)
