### ISSUE TITLE
How do I set a value to DateTimePicker

### ISSUE THREAD

**Issue by svsno1** [m3uzz/date_time_picker#8]
How do I set a value to the DateTimePicker from the outside?
I used setState() to set the initialValue but it hasn't changed.

Thanks for any help.

**Comment by hslbetto** [comment]
If you want to change the value, you need to use the controller instead of initialValue.
See the example app for more details.
https://github.com/m3uzz/date_time_picker/blob/master/example/lib/main.dart

**Comment by melaLetics** [comment]
I have problems setting my initial time following the example app.

I declared 
```
  @override
  void initState() {
    setState(() {
      _timeController = TextEditingController(text: '$_hour:$_minute');
     }
  }
```
with my initial hour and minute (both greater than zero if this information is necessary).

in my form I use
```
  DateTimePicker(
    type: DateTimePickerType.time,
    controller: _timeController,
    cancelText: 'Abbruch',
    icon: Icon(
      Icons.access_time,
      color: Theme.of(context).accentColor,
    ),
    timeLabelText: "Uhrzeit",
    onChanged: (val) => print(val),
    validator: (val) {
      print(val);
      return null;
    },
    onSaved: (val) => print(val),
  ),
```
So no extra magic or something like that - but it doesn't work. I get the runtime error 

 Invalid radix-10 number (at character 1)
null
^
What am I doing wrong?

**Comment by engmsaleh** [comment]
@hslbetto Thanks a lot for the trick it saved my day :D
